version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    ports:
      - "3000:3000"
    environment:
      - PYTHON_SERVICE_URL=http://python-service:5000
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SEARCH_ENGINE_ID=${SEARCH_ENGINE_ID}
    depends_on:
      - python-service

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SEARCH_ENGINE_ID=${SEARCH_ENGINE_ID}
    volumes:
      - ./python-service/data:/app/data

volumes:
  python-data:
